# 配置端口
server:
  port: 8888
  servlet:
    session:
      timeout: 21600

spring:
  application:
    name: blog
  # 数据源及连接池配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/blog?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&serverTimezone=GMT&allowMultiQueries=true
    username: root #root
    password: 123456 #root
  # redis配置
#  redis:
#    host: #hostIP
#    port: 6379
#    password: #密码
  # mq配置
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        retry:
          enabled: true
          max-attempts: 3 #最大重试次数
          initial-interval: 3000 #重试间隔时间（单位毫秒）
  # 邮箱配置
  mail:
    # 配置 SMTP 服务器地址
    host: smtp.qq.com
    # 发送者邮箱
    username: 292812014@qq.com
    # 配置密码，注意不是真正的密码，而是刚刚申请到的授权码
    password: ivthghnojssxdfcc #密码
    # 端口号465或587
    port: 587
    # 默认的邮件编码为UTF-8
    default-encoding: UTF-8
    # 配置SSL 加密工厂
    properties:
      mail:
        smtp:
          socketFactoryClass: javax.net.ssl.SSLSocketFactory
        #表示开启 DEBUG 模式，这样，邮件发送过程的日志会在控制台打印出来，方便排查错误
        debug: true
  # 上传图片大小限制
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

##  # es配置 若搜索模式为mysql可删除
#  elasticsearch:
#    rest:
#      uris: #你的IP:9200

# 搜索模式 mysql
search:
  mode: mysql

#是否开启swagger
swagger:
  isOpen: false

#录入日志级别
log:
  isOpen: ERROR

# 上传模式
upload:
  #选择上传方式
  mode: oss
  local:
    # nginx映射本地文件路径,nginx配置文件中填写的映射路径
    url: http://
    # 本地文件存储路径
    path: /usr/local/upload/
  # 阿里云oss存储配置
  oss:
    url: http://Bucket域名/
    endpoint: oss的secretId
    accessKeyId: oss的secretKey
    accessKeySecret: oss的region
    bucketName: oss的bucketName
 # 腾讯云cos存储配置
  cos:
    url: http://Bucket域名/
    secretId: cos的secretId
    secretKey: cos的secretKey
    region: cos的region
    bucketName: cos的bucketName

# Mybatis-plus配置
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  global-config:
    db-config:
      id-type: AUTO
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

# 网站前台域名（邮件通知用）
website:
  url: http://www.yehonghan.top


#第三方配置信息
qq:
  app-id: QQ APPID
  check-token-url: https://graph.qq.com/oauth2.0/me?access_token={access_token}
  user-info-url: https://graph.qq.com/user/get_user_info?openid={openid}&access_token={access_token}&oauth_consumer_key={oauth_consumer_key}
